name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build --source /DB/BackendDB/  --no-restore --configuration Release
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose --file DB/TestContainer/docker-compose.yml  up -d
